@startuml


class LandingPage {
inputElement : Number
zona configuratii : String
}

class Tablou {
}
LandingPage <|- Tablou
LandingPage <|-- Button
LandingPage <|--Zona
LandingPage <|--Mesaj
Tablou "1" *-- "many"Configuration
class Configuration {
model : String
pret : String
constructor : String
memory : String

checkInput()
getValue()
}

class Button {
continue
add
display
clickContinue()
clickAdd()
clickDisplay()
dispareAdd()
apareDisplay()
}

class Mesaj {
mesajEroare
displayErrorMessage()
}

class Zona {
}

@enduml